// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: service_http_access_log.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建访问日志
type CreateHTTPAccessLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HttpAccessLogs []*HTTPAccessLog `protobuf:"bytes,1,rep,name=httpAccessLogs,proto3" json:"httpAccessLogs,omitempty"`
}

func (x *CreateHTTPAccessLogsRequest) Reset() {
	*x = CreateHTTPAccessLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHTTPAccessLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHTTPAccessLogsRequest) ProtoMessage() {}

func (x *CreateHTTPAccessLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHTTPAccessLogsRequest.ProtoReflect.Descriptor instead.
func (*CreateHTTPAccessLogsRequest) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHTTPAccessLogsRequest) GetHttpAccessLogs() []*HTTPAccessLog {
	if x != nil {
		return x.HttpAccessLogs
	}
	return nil
}

type CreateHTTPAccessLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateHTTPAccessLogsResponse) Reset() {
	*x = CreateHTTPAccessLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHTTPAccessLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHTTPAccessLogsResponse) ProtoMessage() {}

func (x *CreateHTTPAccessLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHTTPAccessLogsResponse.ProtoReflect.Descriptor instead.
func (*CreateHTTPAccessLogsResponse) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{1}
}

// 列出往前的单页访问日志
type ListHTTPAccessLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId           string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`                      // 上一页请求ID，可选
	ServerId            int64  `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`                       // 服务ID
	Size                int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                               // 单页条数
	Day                 string `protobuf:"bytes,4,opt,name=day,proto3" json:"day,omitempty"`                                  // 日期，格式YYYYMMDD
	Reverse             bool   `protobuf:"varint,5,opt,name=reverse,proto3" json:"reverse,omitempty"`                         // 是否反向查找，可选
	HasError            bool   `protobuf:"varint,6,opt,name=hasError,proto3" json:"hasError,omitempty"`                       // 是否有错误，可选
	FirewallPolicyId    int64  `protobuf:"varint,7,opt,name=firewallPolicyId,proto3" json:"firewallPolicyId,omitempty"`       // WAF策略ID，可选
	FirewallRuleGroupId int64  `protobuf:"varint,8,opt,name=firewallRuleGroupId,proto3" json:"firewallRuleGroupId,omitempty"` // WAF分组ID，可选
	FirewallRuleSetId   int64  `protobuf:"varint,9,opt,name=firewallRuleSetId,proto3" json:"firewallRuleSetId,omitempty"`     // WAF规则集ID，可选
	UserId              int64  `protobuf:"varint,10,opt,name=userId,proto3" json:"userId,omitempty"`                          // 用户ID
	HasFirewallPolicy   bool   `protobuf:"varint,11,opt,name=hasFirewallPolicy,proto3" json:"hasFirewallPolicy,omitempty"`    // 是否有WAF策略
	Keyword             string `protobuf:"bytes,12,opt,name=keyword,proto3" json:"keyword,omitempty"`                         // 关键词
	Ip                  string `protobuf:"bytes,13,opt,name=ip,proto3" json:"ip,omitempty"`
	Domain              string `protobuf:"bytes,14,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *ListHTTPAccessLogsRequest) Reset() {
	*x = ListHTTPAccessLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHTTPAccessLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHTTPAccessLogsRequest) ProtoMessage() {}

func (x *ListHTTPAccessLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHTTPAccessLogsRequest.ProtoReflect.Descriptor instead.
func (*ListHTTPAccessLogsRequest) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{2}
}

func (x *ListHTTPAccessLogsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListHTTPAccessLogsRequest) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ListHTTPAccessLogsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListHTTPAccessLogsRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *ListHTTPAccessLogsRequest) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

func (x *ListHTTPAccessLogsRequest) GetHasError() bool {
	if x != nil {
		return x.HasError
	}
	return false
}

func (x *ListHTTPAccessLogsRequest) GetFirewallPolicyId() int64 {
	if x != nil {
		return x.FirewallPolicyId
	}
	return 0
}

func (x *ListHTTPAccessLogsRequest) GetFirewallRuleGroupId() int64 {
	if x != nil {
		return x.FirewallRuleGroupId
	}
	return 0
}

func (x *ListHTTPAccessLogsRequest) GetFirewallRuleSetId() int64 {
	if x != nil {
		return x.FirewallRuleSetId
	}
	return 0
}

func (x *ListHTTPAccessLogsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListHTTPAccessLogsRequest) GetHasFirewallPolicy() bool {
	if x != nil {
		return x.HasFirewallPolicy
	}
	return false
}

func (x *ListHTTPAccessLogsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListHTTPAccessLogsRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ListHTTPAccessLogsRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ListHTTPAccessLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	AccessLogs     []*HTTPAccessLog `protobuf:"bytes,1,rep,name=accessLogs,proto3" json:"accessLogs,omitempty"`
	HttpAccessLogs []*HTTPAccessLog `protobuf:"bytes,4,rep,name=httpAccessLogs,proto3" json:"httpAccessLogs,omitempty"`
	RequestId      string           `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	HasMore        bool             `protobuf:"varint,3,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
}

func (x *ListHTTPAccessLogsResponse) Reset() {
	*x = ListHTTPAccessLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHTTPAccessLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHTTPAccessLogsResponse) ProtoMessage() {}

func (x *ListHTTPAccessLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHTTPAccessLogsResponse.ProtoReflect.Descriptor instead.
func (*ListHTTPAccessLogsResponse) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{3}
}

// Deprecated: Do not use.
func (x *ListHTTPAccessLogsResponse) GetAccessLogs() []*HTTPAccessLog {
	if x != nil {
		return x.AccessLogs
	}
	return nil
}

func (x *ListHTTPAccessLogsResponse) GetHttpAccessLogs() []*HTTPAccessLog {
	if x != nil {
		return x.HttpAccessLogs
	}
	return nil
}

func (x *ListHTTPAccessLogsResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListHTTPAccessLogsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 查找单个日志
type FindHTTPAccessLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
}

func (x *FindHTTPAccessLogRequest) Reset() {
	*x = FindHTTPAccessLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindHTTPAccessLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindHTTPAccessLogRequest) ProtoMessage() {}

func (x *FindHTTPAccessLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindHTTPAccessLogRequest.ProtoReflect.Descriptor instead.
func (*FindHTTPAccessLogRequest) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{4}
}

func (x *FindHTTPAccessLogRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type FindHTTPAccessLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HttpAccessLog *HTTPAccessLog `protobuf:"bytes,1,opt,name=httpAccessLog,proto3" json:"httpAccessLog,omitempty"`
}

func (x *FindHTTPAccessLogResponse) Reset() {
	*x = FindHTTPAccessLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindHTTPAccessLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindHTTPAccessLogResponse) ProtoMessage() {}

func (x *FindHTTPAccessLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindHTTPAccessLogResponse.ProtoReflect.Descriptor instead.
func (*FindHTTPAccessLogResponse) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{5}
}

func (x *FindHTTPAccessLogResponse) GetHttpAccessLog() *HTTPAccessLog {
	if x != nil {
		return x.HttpAccessLog
	}
	return nil
}

// 列出往前的单页访问日志
type SearchHTTPAccessLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"` // 上一页请求ID，可选
	ServerId  int64  `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`  // 服务ID
	Size      int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`          // 单页条数
	Day       string `protobuf:"bytes,4,opt,name=day,proto3" json:"day,omitempty"`             // 日期，格式YYYYMMDD
	UserId    int64  `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`      // 用户ID
	Ip        string `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`               //攻击ip
	Domain    string `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain,omitempty"`       //被攻击域名
	StartAt   uint64 `protobuf:"varint,8,opt,name=startAt,proto3" json:"startAt,omitempty"`    //起始时间
	EndAt     uint64 `protobuf:"varint,9,opt,name=endAt,proto3" json:"endAt,omitempty"`        //结束时间
	Code      string `protobuf:"bytes,10,opt,name=code,proto3" json:"code,omitempty"`          //攻击类型code
}

func (x *SearchHTTPAccessLogsRequest) Reset() {
	*x = SearchHTTPAccessLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchHTTPAccessLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHTTPAccessLogsRequest) ProtoMessage() {}

func (x *SearchHTTPAccessLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHTTPAccessLogsRequest.ProtoReflect.Descriptor instead.
func (*SearchHTTPAccessLogsRequest) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{6}
}

func (x *SearchHTTPAccessLogsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SearchHTTPAccessLogsRequest) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *SearchHTTPAccessLogsRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchHTTPAccessLogsRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *SearchHTTPAccessLogsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchHTTPAccessLogsRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SearchHTTPAccessLogsRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SearchHTTPAccessLogsRequest) GetStartAt() uint64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *SearchHTTPAccessLogsRequest) GetEndAt() uint64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *SearchHTTPAccessLogsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SearchHTTPAccessLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	AccessLogs     []*HTTPAccessLog `protobuf:"bytes,1,rep,name=accessLogs,proto3" json:"accessLogs,omitempty"`
	HttpAccessLogs []*HTTPAccessLog `protobuf:"bytes,4,rep,name=httpAccessLogs,proto3" json:"httpAccessLogs,omitempty"`
	RequestId      string           `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	HasMore        bool             `protobuf:"varint,3,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
}

func (x *SearchHTTPAccessLogsResponse) Reset() {
	*x = SearchHTTPAccessLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchHTTPAccessLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHTTPAccessLogsResponse) ProtoMessage() {}

func (x *SearchHTTPAccessLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHTTPAccessLogsResponse.ProtoReflect.Descriptor instead.
func (*SearchHTTPAccessLogsResponse) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{7}
}

// Deprecated: Do not use.
func (x *SearchHTTPAccessLogsResponse) GetAccessLogs() []*HTTPAccessLog {
	if x != nil {
		return x.AccessLogs
	}
	return nil
}

func (x *SearchHTTPAccessLogsResponse) GetHttpAccessLogs() []*HTTPAccessLog {
	if x != nil {
		return x.HttpAccessLogs
	}
	return nil
}

func (x *SearchHTTPAccessLogsResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SearchHTTPAccessLogsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type StatisticsHTTPAccessTopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day  string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`    //查询日期
	User int64  `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"` //用户id
	Top  int32  `protobuf:"varint,3,opt,name=top,proto3" json:"top,omitempty"`   //排行前几
}

func (x *StatisticsHTTPAccessTopRequest) Reset() {
	*x = StatisticsHTTPAccessTopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsHTTPAccessTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsHTTPAccessTopRequest) ProtoMessage() {}

func (x *StatisticsHTTPAccessTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsHTTPAccessTopRequest.ProtoReflect.Descriptor instead.
func (*StatisticsHTTPAccessTopRequest) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{8}
}

func (x *StatisticsHTTPAccessTopRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *StatisticsHTTPAccessTopRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *StatisticsHTTPAccessTopRequest) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

type StatisticsHTTPAccessTopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip     *AccessTop `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`         //ip排名
	Region *AccessTop `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"` //区域排名
	Total  int64      `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`  //总数
}

func (x *StatisticsHTTPAccessTopResponse) Reset() {
	*x = StatisticsHTTPAccessTopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsHTTPAccessTopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsHTTPAccessTopResponse) ProtoMessage() {}

func (x *StatisticsHTTPAccessTopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsHTTPAccessTopResponse.ProtoReflect.Descriptor instead.
func (*StatisticsHTTPAccessTopResponse) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{9}
}

func (x *StatisticsHTTPAccessTopResponse) GetIp() *AccessTop {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *StatisticsHTTPAccessTopResponse) GetRegion() *AccessTop {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *StatisticsHTTPAccessTopResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AccessTop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names  []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`           //值
	Counts []int64  `protobuf:"varint,2,rep,packed,name=counts,proto3" json:"counts,omitempty"` //次数
}

func (x *AccessTop) Reset() {
	*x = AccessTop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessTop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTop) ProtoMessage() {}

func (x *AccessTop) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTop.ProtoReflect.Descriptor instead.
func (*AccessTop) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{10}
}

func (x *AccessTop) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *AccessTop) GetCounts() []int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type StatisticsHTTPAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Days []string `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`  //查询日期
	User int64    `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"` //用户id
}

func (x *StatisticsHTTPAccessRequest) Reset() {
	*x = StatisticsHTTPAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsHTTPAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsHTTPAccessRequest) ProtoMessage() {}

func (x *StatisticsHTTPAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsHTTPAccessRequest.ProtoReflect.Descriptor instead.
func (*StatisticsHTTPAccessRequest) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{11}
}

func (x *StatisticsHTTPAccessRequest) GetDays() []string {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *StatisticsHTTPAccessRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

type StatisticsHTTPAccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Counts []int64 `protobuf:"varint,1,rep,packed,name=counts,proto3" json:"counts,omitempty"` //次数
}

func (x *StatisticsHTTPAccessResponse) Reset() {
	*x = StatisticsHTTPAccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsHTTPAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsHTTPAccessResponse) ProtoMessage() {}

func (x *StatisticsHTTPAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsHTTPAccessResponse.ProtoReflect.Descriptor instead.
func (*StatisticsHTTPAccessResponse) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{12}
}

func (x *StatisticsHTTPAccessResponse) GetCounts() []int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type StatisticsHTTPAccessTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day  string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`    //查询日期
	User int64  `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"` //用户id
}

func (x *StatisticsHTTPAccessTypeRequest) Reset() {
	*x = StatisticsHTTPAccessTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsHTTPAccessTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsHTTPAccessTypeRequest) ProtoMessage() {}

func (x *StatisticsHTTPAccessTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsHTTPAccessTypeRequest.ProtoReflect.Descriptor instead.
func (*StatisticsHTTPAccessTypeRequest) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{13}
}

func (x *StatisticsHTTPAccessTypeRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *StatisticsHTTPAccessTypeRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

type StatisticsHTTPAccessTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attacks []*HTTPAccessType `protobuf:"bytes,1,rep,name=attacks,proto3" json:"attacks,omitempty"` //攻击
}

func (x *StatisticsHTTPAccessTypeResponse) Reset() {
	*x = StatisticsHTTPAccessTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsHTTPAccessTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsHTTPAccessTypeResponse) ProtoMessage() {}

func (x *StatisticsHTTPAccessTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsHTTPAccessTypeResponse.ProtoReflect.Descriptor instead.
func (*StatisticsHTTPAccessTypeResponse) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{14}
}

func (x *StatisticsHTTPAccessTypeResponse) GetAttacks() []*HTTPAccessType {
	if x != nil {
		return x.Attacks
	}
	return nil
}

type HTTPAccessType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`    //攻击类型分组code
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`    //攻击类型名称
	Count int64  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` //攻击次数
}

func (x *HTTPAccessType) Reset() {
	*x = HTTPAccessType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_http_access_log_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPAccessType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPAccessType) ProtoMessage() {}

func (x *HTTPAccessType) ProtoReflect() protoreflect.Message {
	mi := &file_service_http_access_log_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPAccessType.ProtoReflect.Descriptor instead.
func (*HTTPAccessType) Descriptor() ([]byte, []int) {
	return file_service_http_access_log_proto_rawDescGZIP(), []int{15}
}

func (x *HTTPAccessType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *HTTPAccessType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HTTPAccessType) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_service_http_access_log_proto protoreflect.FileDescriptor

var file_service_http_access_log_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x22, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x6f,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f,
	0x67, 0x52, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67,
	0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x54, 0x54, 0x50, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0xc5, 0x03, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61, 0x73,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c,
	0x6c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x10, 0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49,
	0x64, 0x12, 0x30, 0x0a, 0x13, 0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x52, 0x75, 0x6c,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13,
	0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x52,
	0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11,
	0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x68, 0x61, 0x73,
	0x46, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x68, 0x61, 0x73, 0x46, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c,
	0x6c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xc6, 0x01, 0x0a, 0x1a, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x42,
	0x02, 0x18, 0x01, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x12,
	0x39, 0x0a, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x54, 0x54,
	0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x0e, 0x68, 0x74, 0x74, 0x70,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x4d,
	0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f,
	0x72, 0x65, 0x22, 0x38, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x19,
	0x46, 0x69, 0x6e, 0x64, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x68, 0x74, 0x74,
	0x70, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x4c, 0x6f, 0x67, 0x52, 0x0d, 0x68, 0x74, 0x74, 0x70, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c,
	0x6f, 0x67, 0x22, 0x81, 0x02, 0x0a, 0x1b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x54, 0x54,
	0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x6e, 0x64,
	0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x1c, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x4c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x42, 0x02,
	0x18, 0x01, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x39,
	0x0a, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x54, 0x54, 0x50,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72,
	0x65, 0x22, 0x58, 0x0a, 0x1e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x48,
	0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x6f, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x6f, 0x70, 0x22, 0x7d, 0x0a, 0x1f, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x70, 0x52, 0x02, 0x69, 0x70, 0x12, 0x25, 0x0a,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x70, 0x52, 0x06, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x39, 0x0a, 0x09, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22, 0x45, 0x0a, 0x1b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x79, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x1c,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x22, 0x47, 0x0a, 0x1f, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x50, 0x0a,
	0x20, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x73, 0x22,
	0x4e, 0x0a, 0x0e, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32,
	0x99, 0x05, 0x0a, 0x14, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x14, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73,
	0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x54, 0x54, 0x50,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x54, 0x54,
	0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x6c, 0x69, 0x73, 0x74, 0x48, 0x54, 0x54, 0x50, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x11, 0x66, 0x69, 0x6e, 0x64,
	0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x12, 0x1c, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x14, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f,
	0x67, 0x73, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x54,
	0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48,
	0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x17, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x70,
	0x12, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x14, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x18, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x48, 0x54, 0x54, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_http_access_log_proto_rawDescOnce sync.Once
	file_service_http_access_log_proto_rawDescData = file_service_http_access_log_proto_rawDesc
)

func file_service_http_access_log_proto_rawDescGZIP() []byte {
	file_service_http_access_log_proto_rawDescOnce.Do(func() {
		file_service_http_access_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_http_access_log_proto_rawDescData)
	})
	return file_service_http_access_log_proto_rawDescData
}

var file_service_http_access_log_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_service_http_access_log_proto_goTypes = []interface{}{
	(*CreateHTTPAccessLogsRequest)(nil),      // 0: pb.CreateHTTPAccessLogsRequest
	(*CreateHTTPAccessLogsResponse)(nil),     // 1: pb.CreateHTTPAccessLogsResponse
	(*ListHTTPAccessLogsRequest)(nil),        // 2: pb.ListHTTPAccessLogsRequest
	(*ListHTTPAccessLogsResponse)(nil),       // 3: pb.ListHTTPAccessLogsResponse
	(*FindHTTPAccessLogRequest)(nil),         // 4: pb.FindHTTPAccessLogRequest
	(*FindHTTPAccessLogResponse)(nil),        // 5: pb.FindHTTPAccessLogResponse
	(*SearchHTTPAccessLogsRequest)(nil),      // 6: pb.SearchHTTPAccessLogsRequest
	(*SearchHTTPAccessLogsResponse)(nil),     // 7: pb.SearchHTTPAccessLogsResponse
	(*StatisticsHTTPAccessTopRequest)(nil),   // 8: pb.StatisticsHTTPAccessTopRequest
	(*StatisticsHTTPAccessTopResponse)(nil),  // 9: pb.StatisticsHTTPAccessTopResponse
	(*AccessTop)(nil),                        // 10: pb.AccessTop
	(*StatisticsHTTPAccessRequest)(nil),      // 11: pb.StatisticsHTTPAccessRequest
	(*StatisticsHTTPAccessResponse)(nil),     // 12: pb.StatisticsHTTPAccessResponse
	(*StatisticsHTTPAccessTypeRequest)(nil),  // 13: pb.StatisticsHTTPAccessTypeRequest
	(*StatisticsHTTPAccessTypeResponse)(nil), // 14: pb.StatisticsHTTPAccessTypeResponse
	(*HTTPAccessType)(nil),                   // 15: pb.HTTPAccessType
	(*HTTPAccessLog)(nil),                    // 16: pb.HTTPAccessLog
}
var file_service_http_access_log_proto_depIdxs = []int32{
	16, // 0: pb.CreateHTTPAccessLogsRequest.httpAccessLogs:type_name -> pb.HTTPAccessLog
	16, // 1: pb.ListHTTPAccessLogsResponse.accessLogs:type_name -> pb.HTTPAccessLog
	16, // 2: pb.ListHTTPAccessLogsResponse.httpAccessLogs:type_name -> pb.HTTPAccessLog
	16, // 3: pb.FindHTTPAccessLogResponse.httpAccessLog:type_name -> pb.HTTPAccessLog
	16, // 4: pb.SearchHTTPAccessLogsResponse.accessLogs:type_name -> pb.HTTPAccessLog
	16, // 5: pb.SearchHTTPAccessLogsResponse.httpAccessLogs:type_name -> pb.HTTPAccessLog
	10, // 6: pb.StatisticsHTTPAccessTopResponse.ip:type_name -> pb.AccessTop
	10, // 7: pb.StatisticsHTTPAccessTopResponse.region:type_name -> pb.AccessTop
	15, // 8: pb.StatisticsHTTPAccessTypeResponse.attacks:type_name -> pb.HTTPAccessType
	0,  // 9: pb.HTTPAccessLogService.createHTTPAccessLogs:input_type -> pb.CreateHTTPAccessLogsRequest
	2,  // 10: pb.HTTPAccessLogService.listHTTPAccessLogs:input_type -> pb.ListHTTPAccessLogsRequest
	4,  // 11: pb.HTTPAccessLogService.findHTTPAccessLog:input_type -> pb.FindHTTPAccessLogRequest
	6,  // 12: pb.HTTPAccessLogService.searchHTTPAccessLogs:input_type -> pb.SearchHTTPAccessLogsRequest
	8,  // 13: pb.HTTPAccessLogService.statisticsHTTPAccessTop:input_type -> pb.StatisticsHTTPAccessTopRequest
	11, // 14: pb.HTTPAccessLogService.statisticsHTTPAccess:input_type -> pb.StatisticsHTTPAccessRequest
	13, // 15: pb.HTTPAccessLogService.statisticsHTTPAccessType:input_type -> pb.StatisticsHTTPAccessTypeRequest
	1,  // 16: pb.HTTPAccessLogService.createHTTPAccessLogs:output_type -> pb.CreateHTTPAccessLogsResponse
	3,  // 17: pb.HTTPAccessLogService.listHTTPAccessLogs:output_type -> pb.ListHTTPAccessLogsResponse
	5,  // 18: pb.HTTPAccessLogService.findHTTPAccessLog:output_type -> pb.FindHTTPAccessLogResponse
	7,  // 19: pb.HTTPAccessLogService.searchHTTPAccessLogs:output_type -> pb.SearchHTTPAccessLogsResponse
	9,  // 20: pb.HTTPAccessLogService.statisticsHTTPAccessTop:output_type -> pb.StatisticsHTTPAccessTopResponse
	12, // 21: pb.HTTPAccessLogService.statisticsHTTPAccess:output_type -> pb.StatisticsHTTPAccessResponse
	14, // 22: pb.HTTPAccessLogService.statisticsHTTPAccessType:output_type -> pb.StatisticsHTTPAccessTypeResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_service_http_access_log_proto_init() }
func file_service_http_access_log_proto_init() {
	if File_service_http_access_log_proto != nil {
		return
	}
	file_models_model_http_access_log_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_http_access_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHTTPAccessLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHTTPAccessLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHTTPAccessLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHTTPAccessLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindHTTPAccessLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindHTTPAccessLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchHTTPAccessLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchHTTPAccessLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsHTTPAccessTopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsHTTPAccessTopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessTop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsHTTPAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsHTTPAccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsHTTPAccessTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsHTTPAccessTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_http_access_log_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPAccessType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_http_access_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_http_access_log_proto_goTypes,
		DependencyIndexes: file_service_http_access_log_proto_depIdxs,
		MessageInfos:      file_service_http_access_log_proto_msgTypes,
	}.Build()
	File_service_http_access_log_proto = out.File
	file_service_http_access_log_proto_rawDesc = nil
	file_service_http_access_log_proto_goTypes = nil
	file_service_http_access_log_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HTTPAccessLogServiceClient is the client API for HTTPAccessLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HTTPAccessLogServiceClient interface {
	// 创建访问日志
	CreateHTTPAccessLogs(ctx context.Context, in *CreateHTTPAccessLogsRequest, opts ...grpc.CallOption) (*CreateHTTPAccessLogsResponse, error)
	// 列出单页访问日志
	ListHTTPAccessLogs(ctx context.Context, in *ListHTTPAccessLogsRequest, opts ...grpc.CallOption) (*ListHTTPAccessLogsResponse, error)
	// 查找单个日志
	FindHTTPAccessLog(ctx context.Context, in *FindHTTPAccessLogRequest, opts ...grpc.CallOption) (*FindHTTPAccessLogResponse, error)
	// 列出单页访问日志 新增 时间条件
	SearchHTTPAccessLogs(ctx context.Context, in *SearchHTTPAccessLogsRequest, opts ...grpc.CallOption) (*SearchHTTPAccessLogsResponse, error)
	// 统计用户相关域名的攻击排行（ip/区域）
	StatisticsHTTPAccessTop(ctx context.Context, in *StatisticsHTTPAccessTopRequest, opts ...grpc.CallOption) (*StatisticsHTTPAccessTopResponse, error)
	// 统计指定日期用户相关域名对应的攻击次数
	StatisticsHTTPAccess(ctx context.Context, in *StatisticsHTTPAccessRequest, opts ...grpc.CallOption) (*StatisticsHTTPAccessResponse, error)
	// 统计指定日期用户相关域名对应的攻击类型次数
	StatisticsHTTPAccessType(ctx context.Context, in *StatisticsHTTPAccessTypeRequest, opts ...grpc.CallOption) (*StatisticsHTTPAccessTypeResponse, error)
}

type hTTPAccessLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHTTPAccessLogServiceClient(cc grpc.ClientConnInterface) HTTPAccessLogServiceClient {
	return &hTTPAccessLogServiceClient{cc}
}

func (c *hTTPAccessLogServiceClient) CreateHTTPAccessLogs(ctx context.Context, in *CreateHTTPAccessLogsRequest, opts ...grpc.CallOption) (*CreateHTTPAccessLogsResponse, error) {
	out := new(CreateHTTPAccessLogsResponse)
	err := c.cc.Invoke(ctx, "/pb.HTTPAccessLogService/createHTTPAccessLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPAccessLogServiceClient) ListHTTPAccessLogs(ctx context.Context, in *ListHTTPAccessLogsRequest, opts ...grpc.CallOption) (*ListHTTPAccessLogsResponse, error) {
	out := new(ListHTTPAccessLogsResponse)
	err := c.cc.Invoke(ctx, "/pb.HTTPAccessLogService/listHTTPAccessLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPAccessLogServiceClient) FindHTTPAccessLog(ctx context.Context, in *FindHTTPAccessLogRequest, opts ...grpc.CallOption) (*FindHTTPAccessLogResponse, error) {
	out := new(FindHTTPAccessLogResponse)
	err := c.cc.Invoke(ctx, "/pb.HTTPAccessLogService/findHTTPAccessLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPAccessLogServiceClient) SearchHTTPAccessLogs(ctx context.Context, in *SearchHTTPAccessLogsRequest, opts ...grpc.CallOption) (*SearchHTTPAccessLogsResponse, error) {
	out := new(SearchHTTPAccessLogsResponse)
	err := c.cc.Invoke(ctx, "/pb.HTTPAccessLogService/searchHTTPAccessLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPAccessLogServiceClient) StatisticsHTTPAccessTop(ctx context.Context, in *StatisticsHTTPAccessTopRequest, opts ...grpc.CallOption) (*StatisticsHTTPAccessTopResponse, error) {
	out := new(StatisticsHTTPAccessTopResponse)
	err := c.cc.Invoke(ctx, "/pb.HTTPAccessLogService/statisticsHTTPAccessTop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPAccessLogServiceClient) StatisticsHTTPAccess(ctx context.Context, in *StatisticsHTTPAccessRequest, opts ...grpc.CallOption) (*StatisticsHTTPAccessResponse, error) {
	out := new(StatisticsHTTPAccessResponse)
	err := c.cc.Invoke(ctx, "/pb.HTTPAccessLogService/statisticsHTTPAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPAccessLogServiceClient) StatisticsHTTPAccessType(ctx context.Context, in *StatisticsHTTPAccessTypeRequest, opts ...grpc.CallOption) (*StatisticsHTTPAccessTypeResponse, error) {
	out := new(StatisticsHTTPAccessTypeResponse)
	err := c.cc.Invoke(ctx, "/pb.HTTPAccessLogService/statisticsHTTPAccessType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPAccessLogServiceServer is the server API for HTTPAccessLogService service.
type HTTPAccessLogServiceServer interface {
	// 创建访问日志
	CreateHTTPAccessLogs(context.Context, *CreateHTTPAccessLogsRequest) (*CreateHTTPAccessLogsResponse, error)
	// 列出单页访问日志
	ListHTTPAccessLogs(context.Context, *ListHTTPAccessLogsRequest) (*ListHTTPAccessLogsResponse, error)
	// 查找单个日志
	FindHTTPAccessLog(context.Context, *FindHTTPAccessLogRequest) (*FindHTTPAccessLogResponse, error)
	// 列出单页访问日志 新增 时间条件
	SearchHTTPAccessLogs(context.Context, *SearchHTTPAccessLogsRequest) (*SearchHTTPAccessLogsResponse, error)
	// 统计用户相关域名的攻击排行（ip/区域）
	StatisticsHTTPAccessTop(context.Context, *StatisticsHTTPAccessTopRequest) (*StatisticsHTTPAccessTopResponse, error)
	// 统计指定日期用户相关域名对应的攻击次数
	StatisticsHTTPAccess(context.Context, *StatisticsHTTPAccessRequest) (*StatisticsHTTPAccessResponse, error)
	// 统计指定日期用户相关域名对应的攻击类型次数
	StatisticsHTTPAccessType(context.Context, *StatisticsHTTPAccessTypeRequest) (*StatisticsHTTPAccessTypeResponse, error)
}

// UnimplementedHTTPAccessLogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHTTPAccessLogServiceServer struct {
}

func (*UnimplementedHTTPAccessLogServiceServer) CreateHTTPAccessLogs(context.Context, *CreateHTTPAccessLogsRequest) (*CreateHTTPAccessLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHTTPAccessLogs not implemented")
}
func (*UnimplementedHTTPAccessLogServiceServer) ListHTTPAccessLogs(context.Context, *ListHTTPAccessLogsRequest) (*ListHTTPAccessLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHTTPAccessLogs not implemented")
}
func (*UnimplementedHTTPAccessLogServiceServer) FindHTTPAccessLog(context.Context, *FindHTTPAccessLogRequest) (*FindHTTPAccessLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindHTTPAccessLog not implemented")
}
func (*UnimplementedHTTPAccessLogServiceServer) SearchHTTPAccessLogs(context.Context, *SearchHTTPAccessLogsRequest) (*SearchHTTPAccessLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchHTTPAccessLogs not implemented")
}
func (*UnimplementedHTTPAccessLogServiceServer) StatisticsHTTPAccessTop(context.Context, *StatisticsHTTPAccessTopRequest) (*StatisticsHTTPAccessTopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatisticsHTTPAccessTop not implemented")
}
func (*UnimplementedHTTPAccessLogServiceServer) StatisticsHTTPAccess(context.Context, *StatisticsHTTPAccessRequest) (*StatisticsHTTPAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatisticsHTTPAccess not implemented")
}
func (*UnimplementedHTTPAccessLogServiceServer) StatisticsHTTPAccessType(context.Context, *StatisticsHTTPAccessTypeRequest) (*StatisticsHTTPAccessTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatisticsHTTPAccessType not implemented")
}

func RegisterHTTPAccessLogServiceServer(s *grpc.Server, srv HTTPAccessLogServiceServer) {
	s.RegisterService(&_HTTPAccessLogService_serviceDesc, srv)
}

func _HTTPAccessLogService_CreateHTTPAccessLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHTTPAccessLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPAccessLogServiceServer).CreateHTTPAccessLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HTTPAccessLogService/CreateHTTPAccessLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPAccessLogServiceServer).CreateHTTPAccessLogs(ctx, req.(*CreateHTTPAccessLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPAccessLogService_ListHTTPAccessLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHTTPAccessLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPAccessLogServiceServer).ListHTTPAccessLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HTTPAccessLogService/ListHTTPAccessLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPAccessLogServiceServer).ListHTTPAccessLogs(ctx, req.(*ListHTTPAccessLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPAccessLogService_FindHTTPAccessLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindHTTPAccessLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPAccessLogServiceServer).FindHTTPAccessLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HTTPAccessLogService/FindHTTPAccessLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPAccessLogServiceServer).FindHTTPAccessLog(ctx, req.(*FindHTTPAccessLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPAccessLogService_SearchHTTPAccessLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchHTTPAccessLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPAccessLogServiceServer).SearchHTTPAccessLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HTTPAccessLogService/SearchHTTPAccessLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPAccessLogServiceServer).SearchHTTPAccessLogs(ctx, req.(*SearchHTTPAccessLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPAccessLogService_StatisticsHTTPAccessTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsHTTPAccessTopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPAccessLogServiceServer).StatisticsHTTPAccessTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HTTPAccessLogService/StatisticsHTTPAccessTop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPAccessLogServiceServer).StatisticsHTTPAccessTop(ctx, req.(*StatisticsHTTPAccessTopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPAccessLogService_StatisticsHTTPAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsHTTPAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPAccessLogServiceServer).StatisticsHTTPAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HTTPAccessLogService/StatisticsHTTPAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPAccessLogServiceServer).StatisticsHTTPAccess(ctx, req.(*StatisticsHTTPAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPAccessLogService_StatisticsHTTPAccessType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsHTTPAccessTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPAccessLogServiceServer).StatisticsHTTPAccessType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HTTPAccessLogService/StatisticsHTTPAccessType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPAccessLogServiceServer).StatisticsHTTPAccessType(ctx, req.(*StatisticsHTTPAccessTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HTTPAccessLogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HTTPAccessLogService",
	HandlerType: (*HTTPAccessLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createHTTPAccessLogs",
			Handler:    _HTTPAccessLogService_CreateHTTPAccessLogs_Handler,
		},
		{
			MethodName: "listHTTPAccessLogs",
			Handler:    _HTTPAccessLogService_ListHTTPAccessLogs_Handler,
		},
		{
			MethodName: "findHTTPAccessLog",
			Handler:    _HTTPAccessLogService_FindHTTPAccessLog_Handler,
		},
		{
			MethodName: "searchHTTPAccessLogs",
			Handler:    _HTTPAccessLogService_SearchHTTPAccessLogs_Handler,
		},
		{
			MethodName: "statisticsHTTPAccessTop",
			Handler:    _HTTPAccessLogService_StatisticsHTTPAccessTop_Handler,
		},
		{
			MethodName: "statisticsHTTPAccess",
			Handler:    _HTTPAccessLogService_StatisticsHTTPAccess_Handler,
		},
		{
			MethodName: "statisticsHTTPAccessType",
			Handler:    _HTTPAccessLogService_StatisticsHTTPAccessType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_http_access_log.proto",
}
